name: Build

on:
  workflow_call:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: |
          npm ci --force --no-audit --no-fund
          npm install deepsight.gg@latest --save --no-audit --no-fund --prefer-online
        
      - name: Calculate Run Number
        env:
          NUM: ${{ github.run_number }}
        run: echo "BUILD_NUMBER=$(($NUM+447))" >> "$GITHUB_ENV"

      - name: Download testiny artifact
        uses: actions/download-artifact@v4
        with:
          name: testiny-data
          path: static/testiny

      - name: Build
        env:
          DEEPSIGHT_PATH: https://deepsight.gg/
          DEEPSIGHT_BUNGIE_CLIENT_ID: ${{ vars.DEEPSIGHT_BUNGIE_CLIENT_ID }}
          DEEPSIGHT_BUNGIE_API_KEY: ${{ secrets.DEEPSIGHT_BUNGIE_API_KEY }}
          DEEPSIGHT_BUNGIE_API_SECRET: ${{ secrets.DEEPSIGHT_BUNGIE_API_SECRET }}
          DEEPSIGHT_BUILD_NUMBER: ${{ env.BUILD_NUMBER }}
          DEEPSIGHT_BUILD_SHA: ${{ github.sha }}
        run: npm run build

      - name: Cleanup
        run: rm -rf docs/testiny

      - name: Prepare for GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v4
        with:
          fqdn: deepsight.gg
          target_branch: build
          build_dir: docs
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
