name: Check manifest for updates

on:
  push:
    branches: [ manifest ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    - cron: '3/5 * * * *'

concurrency: 
  group: check-manifest

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: manifest

      - name: Setup Node.js environment
        uses: actions/setup-node@v3

      - name: Check updated
        id: updated
        env:
          DEEPSIGHT_MANIFEST_API_KEY: ${{ secrets.DEEPSIGHT_MANIFEST_API_KEY }}
          DEEPSIGHT_MANIFEST_NO_INCREMENT_VERSION: true
        run: node check.js
        continue-on-error: true

      - name: Save versions.json artifact
        uses: actions/upload-artifact@v3
        with:
          name: versions
          path: versions.json

    outputs:
      updated: ${{ steps.updated.outcome }}

  manifest:
    needs: check
    if: ${{ needs.check.outputs.updated != 'failure' }}
    uses: ./.github/workflows/manifest.yml
    secrets: inherit

  deploy:
    needs: manifest
    uses: ./.github/workflows/deploy.yml  
    secrets: inherit
