name: Check manifest for updates

on:
  push:
    branches: [ manifest ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    - cron: '3/5 * * * *'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: manifest

      - name: Setup Node.js environment
        uses: actions/setup-node@v3

      - name: Check updated
        id: updated
        env:
          DEEPSIGHT_MANIFEST_API_KEY: ${{ secrets.DEEPSIGHT_MANIFEST_API_KEY }}
        run: node check.js
        continue-on-error: true
      
      - name: Commit
        run: |
          if [[ -n $(git diff) ]]; then
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add .
            git commit -m "Updated reference PGCR"
            git push
          else
            echo "No changes to commit"
          fi
        
    outputs:
      updated: ${{ steps.updated.outcome }}

  manifest:
    needs: check
    if: ${{ needs.check.outputs.updated != 'failure' }}
    uses: ./.github/workflows/manifest.yml

  deploy:
    needs: manifest
    uses: ./.github/workflows/deploy.yml  
