name: Check manifest for updates

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # schedule:
  #   - cron: '3/5 * * * *'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - uses: actions/checkout@v4
        with:
          ref: manifest
          path: manifest

      - name: Setup Node.js environment
        uses: actions/setup-node@v3

      - name: Check updated
        id: updated
        run: node tasks/manifest.js
        continue-on-error: true
        
    outputs:
      updated: ${{ steps.updated.outcome != 'failure' }}

  manifest:
    if: jobs.check.outputs.updated
    needs: check
    uses: ./.github/workflows/manifest.yml
    
  deploy:
    if: jobs.check.outputs.updated
    needs: manifest
    uses: ./.github/workflows/deploy.yml  
