name: Deploy

on:
  workflow_call:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout build
        uses: actions/checkout@v2
        with:
          ref: build
          
      - name: Checkout build-beta
        uses: actions/checkout@v2
        with:
          ref: build-beta
          path: beta
      
      - name: Prepare for GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: deploy
          build_dir: "."
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
