name: Deploy
concurrency:
  group: deploy
  cancel-in-progress: true

on:
  workflow_call:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout build
        uses: actions/checkout@v4
        with:
          ref: build

      - name: Checkout build-beta
        uses: actions/checkout@v4
        with:
          ref: build-beta
          path: beta

      - name: Checkout manifest
        uses: actions/checkout@v4
        with:
          ref: manifest
          path: manifest

      - name: Checkout images
        uses: actions/checkout@v4
        with:
          ref: generated
          path: generated

      - name: Checkout manifest to beta
        uses: actions/checkout@v4
        with:
          ref: manifest
          path: beta/manifest

      - name: Clear .git folders (no submodules here!)
        run: |
          rm -rf .git
          rm -rf beta/.git
          rm -rf manifest/.git
          rm -rf beta/manifest/.git
          rm -rf generated/.git

      - name: Put generated images in place
        run: |
          mkdir -p image/generated
          cp -r generated/* image/generated/
          rm -rf generated
      
      - name: Prepare for GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: deploy
          build_dir: "."
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
