name: Manifest
concurrency: ${{ github.ref }}

on:
  workflow_call:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  manifest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          ref: manifest
          path: manifest

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci --force
        
      - name: Refresh token
        id: refresh_token
        env:
          DEEPSIGHT_MANIFEST_API_KEY: ${{ secrets.DEEPSIGHT_MANIFEST_API_KEY }}
          DEEPSIGHT_MANIFEST_CLIENT_ID: ${{ vars.DEEPSIGHT_MANIFEST_CLIENT_ID }}
          DEEPSIGHT_MANIFEST_CLIENT_SECRET: ${{ secrets.DEEPSIGHT_MANIFEST_CLIENT_SECRET }}
          DEEPSIGHT_MANIFEST_USER_ACCESS_TOKEN: ${{ secrets.DEEPSIGHT_MANIFEST_USER_ACCESS_TOKEN }}
          DEEPSIGHT_MANIFEST_USER_REFRESH_TOKEN: ${{ secrets.DEEPSIGHT_MANIFEST_USER_REFRESH_TOKEN }}
          DEEPSIGHT_MANIFEST_USER_MEMBERSHIP_TYPE: ${{ vars.DEEPSIGHT_MANIFEST_USER_MEMBERSHIP_TYPE }}
          DEEPSIGHT_MANIFEST_USER_MEMBERSHIP_ID: ${{ secrets.DEEPSIGHT_MANIFEST_USER_MEMBERSHIP_ID }}
        run: npm run refresh_token
        
      - name: Update access token
        if: ${{ steps.refresh_token.outputs != null && steps.refresh_token.outputs.access_token != null }}
        uses: action-pack/set-secret@v1
        with:
          name: 'DEEPSIGHT_MANIFEST_USER_ACCESS_TOKEN'
          value: ${{ steps.refresh_token.outputs.access_token }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          
      - name: Update refresh token
        if: ${{ steps.refresh_token.outputs != null && steps.refresh_token.outputs.refresh_token != null }}
        uses: action-pack/set-secret@v1
        with:
          name: 'DEEPSIGHT_MANIFEST_USER_REFRESH_TOKEN'
          value: ${{ steps.refresh_token.outputs.refresh_token }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Download versions artifact
        uses: actions/download-artifact@v4
        with:
          name: versions
          path: manifest
        continue-on-error: true

      - name: Manifest
        env:
          DEEPSIGHT_BUNGIE_CLIENT_ID: ${{ vars.DEEPSIGHT_BUNGIE_CLIENT_ID }}
          DEEPSIGHT_BUNGIE_API_KEY: ${{ secrets.DEEPSIGHT_BUNGIE_API_KEY }}
          DEEPSIGHT_BUNGIE_API_SECRET: ${{ secrets.DEEPSIGHT_BUNGIE_API_SECRET }}
          DEEPSIGHT_MANIFEST_API_KEY: ${{ secrets.DEEPSIGHT_MANIFEST_API_KEY }}
          DEEPSIGHT_MANIFEST_CLIENT_ID: ${{ vars.DEEPSIGHT_MANIFEST_CLIENT_ID }}
          DEEPSIGHT_MANIFEST_CLIENT_SECRET: ${{ secrets.DEEPSIGHT_MANIFEST_CLIENT_SECRET }}
          DEEPSIGHT_MANIFEST_USER_ACCESS_TOKEN: ${{ secrets.DEEPSIGHT_MANIFEST_USER_ACCESS_TOKEN }}
          DEEPSIGHT_MANIFEST_USER_REFRESH_TOKEN: ${{ secrets.DEEPSIGHT_MANIFEST_USER_REFRESH_TOKEN }}
          DEEPSIGHT_MANIFEST_USER_MEMBERSHIP_TYPE: ${{ vars.DEEPSIGHT_MANIFEST_USER_MEMBERSHIP_TYPE }}
          DEEPSIGHT_MANIFEST_USER_MEMBERSHIP_ID: ${{ secrets.DEEPSIGHT_MANIFEST_USER_MEMBERSHIP_ID }}
          DEEPSIGHT_BUILD_NUMBER: ${{ env.BUILD_NUMBER }}
          DEEPSIGHT_BUILD_SHA: ${{ github.sha }}
        run: npm run manifest
        
      - name: Commit & Publish
        run: |
          cd manifest
          if [[ -n $(git diff) ]]; then
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add .
            git commit -m "Updated manifests"
            git push
            npm publish
          else
            echo "No changes to commit & publish"
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Save testiny artifact
        if: github.event_name != 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: testiny-data
          path: static/testiny
