name: Manifest
concurrency: ${{ github.ref }}

on:
  workflow_call:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  manifest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          ref: manifest
          path: manifest

      - name: Setup Node.js environment
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm install

      - name: Manifest
        env:
          DEEPSIGHT_BUNGIE_CLIENT_ID: ${{ secrets.DEEPSIGHT_BUNGIE_CLIENT_ID }}
          DEEPSIGHT_BUNGIE_API_KEY: ${{ secrets.DEEPSIGHT_BUNGIE_API_KEY }}
          DEEPSIGHT_BUNGIE_API_SECRET: ${{ secrets.DEEPSIGHT_BUNGIE_API_SECRET }}
          DEEPSIGHT_BUILD_NUMBER: ${{ env.BUILD_NUMBER }}
          DEEPSIGHT_BUILD_SHA: ${{ github.sha }}
        run: npm run manifest
        
      - name: Commit
        run: |
          cd manifest
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Updated manifests"
          git push
