name: Push main

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  rebase:
    uses: ./.github/workflows/rebase-beta.yml
    secrets: inherit
    
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
    
  build-beta:
    needs: rebase
    if: always()
    uses: ./.github/workflows/build-beta.yml
    secrets: inherit
    
  manifest:
    uses: ./.github/workflows/manifest.yml
    secrets: inherit
    
  deploy:
    needs: [build-beta, build, manifest]
    if: always() && needs.build.result == 'success' && needs.manifest.result == 'success'
    uses: ./.github/workflows/deploy.yml  
