name: Push main

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: push
  cancel-in-progress: true

jobs:
  manifest:
    uses: ./.github/workflows/manifest.yml
    secrets: inherit

  rebase:
    needs: manifest
    uses: ./.github/workflows/rebase-beta.yml
    secrets: inherit
    
  build:
    needs: manifest
    uses: ./.github/workflows/build.yml
    secrets: inherit
    
  build-beta:
    needs: [manifest, rebase]
    if: always() && needs.manifest.result == 'success'
    uses: ./.github/workflows/build-beta.yml
    secrets: inherit
    
  deploy:
    needs: [build-beta, build, manifest]
    if: always() && needs.build.result == 'success' && needs.manifest.result == 'success'
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    
  cleanup:
    needs: deploy
    if: always()
    uses: ./.github/workflows/cleanup.yml
    secrets: inherit
