name: Auto-rebase beta onto main

on:
  workflow_call:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  rebase:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: beta

      - name: Rebase
        run: |
          git fetch
          if ! git rebase origin/main; then
            echo "Rebase failed due to conflicts."
            git rebase --abort
            exit 1
          fi
          
          git push -f origin beta
