name: Auto-rebase beta onto main

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  rebase:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: beta

      - name: Rebase
        run: |
          git rebase main
          git push -f origin beta
